### ISSUE TITLE
landing page results?

### ISSUE THREAD

**Issue by robbobfrh84** [eamoses/tiny-desk#3]
we could have a search for "" when document mounts to have some results show up? idk, you decision...?

**Comment by eamoses** [comment]
We could design it like Google.
Before search:

<img width="1010" alt="Screen Shot 2020-10-16 at 2 36 57 PM" src="https://user-images.githubusercontent.com/15112013/96301736-3a859280-0fbd-11eb-913b-0837880fb616.png">


After search:

<img width="772" alt="Screen Shot 2020-10-16 at 2 37 27 PM" src="https://user-images.githubusercontent.com/15112013/96301747-3fe2dd00-0fbd-11eb-9350-de5049eadaeb.png">

**Comment by eamoses** [comment]
Closing in favor of #13
