### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by robbobfrh84** [eamoses/tiny-desk#6]
That 8x8 pixel i have on tobob.earth?

**Comment by robbobfrh84** [comment]
for phun, add when loading next 10 results?

**Comment by eamoses** [comment]
Let's keep this one in the back of our minds for now. I like the way the page is rendering currently but it doesn't mean we won't want it sometime in the future.

**Comment by eamoses** [comment]
Maybe relating to #13

**Comment by robbobfrh84** [comment]
Realize there's nothing to load for atm....
